function results = cropIm(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% Replace the sample below with your code----------------------------------

% [w, h] is the width and height of original graph
w = size(im, 1);
h = size(im, 2);
% »ñÈ¡resizeºóµÄ´óÐ¡ [maxw, maxh]
if numel(wh) == 1
    if w > h
        maxw = wh;
        maxh = wh*h/w;
    else
        maxh = wh;
        maxw = wh*w/h;
    end
else
    maxw = wh(1);
    maxh = wh(2);
    if (w-h)*(maxw-maxh) < 0
        [maxw, maxh] = deal(h, w);
    end
    
    if w/h < maxw/maxh
        maxw = maxh*w/h;
    else
        maxh = maxw*h/w;
    end
end
if maxw < w
    im = imresize(im, [maxw, maxh]);
end

results.im = im;

%--------------------------------------------------------------------------
