function results = cropIm(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% Replace the sample below with your code----------------------------------
limit = 512; % alexnet's input size

% [w, h] is the width and height of original graph
w = size(im, 1);
h = size(im, 2);

if w > h % wide image
    maxw = limit;
    maxh = limit*h/w;
else     % tall image
    maxh = limit;
    maxw = limit*w/h;
end

% shrink/expand it
im = imresize(im, [maxw, maxh]);


% pad it
im = padarray(im, ...
    [ceil((limit - maxw)/2), ...
    ceil((limit - maxh)/2)...
    ]);

% make sure it's actually correct size
im = imresize(im, [limit, limit]);

results.im = im;  

%--------------------------------------------------------------------------
